spring:

  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.sparta.backend.MySQLCustom.MySQL8DialectCustom
        format_sql: true
        highlight_sql: true

  datasource:
    url: ${{ secrets.SPRING_DATABASE_URL}}
    username: ${{ secrets.SPRING_DATASOURCE_USERNAME}}
    password: ${{ secrets.SPRING_DATASOURCE_PASSWORD}}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${{ secrets.SPRING_MAIL_USERNAME}}
    password: ${{ secrets.SPRING_MAIL_PASSWORD}}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

cloud:
  aws:
    credentials:
      access-key: ${{ secrets.CLOUD_AWS_S3_CREDENTIALS_ACCESS_KEY}}
      secret-key: ${{ secrets.CLOUD_AWS_S3_CREDENTIALS_SECRET_KEY}}
    s3:
      bucket: ${{ secrets.CLOUD_AWS_S3_BUCKET}}
    region:
      auto: false
      static: ${{ secrets.CLOUD_AWS_REGION_STATIC}}
    stack:
      auto: false

logging:
  level:
    org:
      hibernate: info
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

secret-key: ${{ secrets.JWT_SECRET_KEY}}

client-id: ${{ secrets.KAKAO_CLIENT_ID}}
