spring:

  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  datasource:
    url: jdbc:mysql://hanghae99-bubbled.cf4mygpz7zqf.ap-northeast-2.rds.amazonaws.com:3306/hanghae99bubbled
    username: leeyuwk
    password: dlduddnr1!

  mail:
    host: smtp.gmail.com
    port: 587
    username: bubbledreminder@gmail.com
    password: pqfamxbwsebtarvn
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          enable: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

cloud:
  aws:
    credentials:
      access-key: AKIA2OHVHMAZ7QOIQ7XF
      secret-key: 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
    s3:
      bucket: bubbled-profile
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false


logging:
  level:
    org:
      hibernate: info
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

secret-key: myteamisamazing

client-id: 1d78cff847165a34064e2855eaa965d8