# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Set properties
      uses: microsoft/variable-substitution@v1
      with:
        files: ./src/main/resources/application-prod.yml
      env:
        spring.datasource.url: ${{ secrets.SPRING_DATABASE_URL }}
        spring.datasource.username: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
        spring.datasource.password: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
        cloud.aws.credentials.access-key: ${{ secrets.CLOUD_AWS_S3_CREDENTIALS_ACCESS_KEY }}
        cloud.aws.credentials.secret-key: ${{ secrets.CLOUD_AWS_S3_CREDENTIALS_SECRET_KEY }}
        cloud.aws.s3.bucket: ${{ secrets.CLOUD_AWS_S3_BUCKET }}
        cloud.aws.region.static: ${{ secrets.CLOUD_AWS_REGION_STATIC }}
        spring.mail.username: ${{ secrets.SPRING_MAIL_USERNAME }}
        spring.mail.password: ${{ secrets.SPRING_MAIL_PASSWORD }}
        secret-key: ${{ secrets.JWT_SECRET_KEY }}
        client-id: ${{ secrets.KAKAO_CLIENT_ID }}
        
    - name: Build with Gradle
      run: ./gradlew clean build

    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy

    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy
      
    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy
      
    # script files 복사
    - name: Copy script
      run: cp ./scripts/*.sh ./deploy

    # 파일 압축
    - name: Make zip file
      run: zip -r ./bubbled.zip ./deploy

    # Deploy
    - name: Deploy
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CLOUD_AWS_S3_CREDENTIALS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.CLOUD_AWS_S3_CREDENTIALS_SECRET_KEY }}
        aws-region: ${{ secrets.CLOUD_AWS_REGION_STATIC }}

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 --acl private ./bubbled.zip s3://bubbled-deploy/
      
    - name: CodeDeploy
      run: aws deploy create-deployment --application-name Bubbled-codedeploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name bubbled-deploy-group --s3-location bucket=bubbled-deploy,bundleType=zip,key=bubbled.zip
